### ISSUE TITLE
Support dynamic test configurations for EntityManager

### ISSUE THREAD

**Issue by erard22** [dadrus/jpa-unit#34]
Hi, 

it's more a question than an issue. Or maybe both. I like your Junit5 extension and just wanted to integrate it into one of my projects. I didn't find a proper way to setup the database connection dynamically while startup time instead of configure it in persistence.xml. This is the best way I found: 

   ```
@PersistenceContext(unitName = "test-unit")
    private` EntityManagerFactory emf;


    @BeforeEach
    void before() {
        Map<String, Object> p = emf.getProperties();
        p.put("javax.persistence.jdbc.url", System.getProperty("javax.persistence.jdbc.url"));
        p.put("javax.persistence.jdbc.user", System.getProperty("javax.persistence.jdbc.user"));
        p.put("javax.persistence.jdbc.password", System.getProperty("javax.persistence.jdbc.password"));
    }
```

Is there a more proper solution?

Thanks, 

Mike

**Comment by dadrus** [comment]
Hi @erard22,

Actually the annotation `@PersistenceContext` should not work with `EntityManagerFactory`, rather with `EntityManager`. So I wonder, whether the snipped, you've posted, is working. But despite this, `@PersistenceContext` allows to configure the properties, you mentioned by using the `properties` attribute of this annotation. So you should be able to do the following:

```java
@PersistenceContext(unitName = "test-unit", properties = {
    @PersistenceProperty(name="javax.persistence.jdbc.url", value="<your url here>"),
    @PersistenceProperty(name="javax.persistence.jdbc.user", value="<your user here>"),
    @PersistenceProperty(name="javax.persistence.jdbc.password", value="<your pass here>"),
})
private EntityManager manager;
```

Every property one supplies using the `properties` attribute will not be overwritten by the settings in the `persistence.xml`. Unfortunately you cannot do this for `EntityManagerFactory` as the `@PersistenceUnit` annotation does not allow to provide any properties to the JPA provider, thus jpa-unit does not have access to them as well.

You can of course also enable filtering of the `persistence.xml` in your e.g. `pom.xml` to set the relevant properties based on your environment settings like you did it in you example. Or do I somehow misunderstand your question about the dynamics of setting the required connection properties?

**Comment by erard22** [comment]
You're right, the code I posted was wrong. I used the `@PersistenceUnit` annotation there. I copy pasted the wrong code.
Your solution does not solve my issue. What I want is to set the properties from outside, because my database settings are dynamic. With every testrun I get a temporary database assigned and have to change the test settings. The `@PersistenceProperty` annotation does not work, because I cannot use dynamic values there such like `System.getProperty("javax.persistence.jdbc.url)`
I could modify with maven the `persistence.xml`, but this would not be my preferred solution.

**Comment by dadrus** [comment]
Unfortunately I have to disappoint you - the functionality, you are asking is not present today. That doesn't however mean, it connot be introduced. 

If you have some ideas on how to implement it in sense of usage (API wise), I would be glad to read about it.

**Comment by dadrus** [comment]
One Idea from my side would be to introduce support for environment variables using `${env variable name}` syntax for `@PersistenceProperty`. So one could write something like this:

```java
@PersistenceContext(unitName = "test-unit", properties = {
    @PersistenceProperty(name="javax.persistence.jdbc.url", value="${env variable for url}"),
    @PersistenceProperty(name="javax.persistence.jdbc.user", value="${env variable for user}"),
    @PersistenceProperty(name="javax.persistence.jdbc.password", value="${env variable for pass}"),
})
private EntityManager manager;
```

**Comment by dadrus** [comment]
... I lost the part, that you are using `EntityManagerFactory`. Sorry. To configure `EntityManagerFactory` the above approach will not fly, but one could introduce a dedicated annotation, which could be used for both `EntityManager` and `EntityManagerFactory`. E.g.

```java
@PersistenceUnit(unitName = "test-unit")
@PersistenceProvicerConfiguration( {
    @PersistenceProperty(name="javax.persistence.jdbc.url", value="${env variable for url}"),
    @PersistenceProperty(name="javax.persistence.jdbc.user", value="${env variable for user}"),
    @PersistenceProperty(name="javax.persistence.jdbc.password", value="${env variable for pass}"),
})
private EntityManagerFactory factory;
```

Maybe you see better approaches.

**Comment by dadrus** [comment]
Just a side note: the effort to support that kind of configuration is pretty low. So, if we have an agreement about the api, it is just a matter to find some time to implement it. If you like, you can file a pull request as well.

**Comment by erard22** [comment]
Yeah I also think that it's not a big deal. I will fix it using the property replacement solution and make a pull request. Unfortunately it will take some days, but don't worry, it will come.
